### ISSUE TITLE
Enhancements and errors on first test

### ISSUE THREAD

**Issue by BenjaminJoly** [CASES-LU/Fit4Cybersecurity#1]
- [x] Answer in the report is always the same.
- [x] Create sectors in the database
- [x] Categories should appear in the recommendation tab part. Example :

| 1. | **Rules/Charter** |
| --- | --- |
| | Rules (organisational, IT or working ones) should be known and explained to everyone, at the very least orally. Rules that are too long or too heavy with technical vocabulary could become confusing. |
- [x] A percentage should be calculated instead of showing the true score on the chart, even if the categories are not worth the same points
- [x] Encode user_id when we generate an email to contact us for a diagnostic.
- [x] The result chart shouldn't have a target, it should never be changed. (But we can add an average per sector figure later to compare with).
- [x] When a unique answer is clicked, other choices should become grey to warn that they can't be clicked (and if it's possible, couldn't be clickable anymore) and make button colour more grey.
- [x] The Fit4Cybersecurity logo is always in French in the report
- [x] Report name at download should be change (`result-[lang]` could become `Report_Fit4Cybersecurity_[date]_[lang]` for instance)
- [x] Chart categories order are not the same in the report, which could be confusing.

**Comment by ruslanbaydan** [comment]
- _Sectors are still the ones we used for tests_ - **@BenjaminJoly , could you provide the list of new ones.**
- _When you have started the survey, and you click on the logo, the survey just ends without any warning or time to take the user ID. There should be at least a warning when clicking on the logo, or even the "Continue later" menu._ - **DONE: Added a prompt popup to confirm leaving the survey or results page.**
- _When nothing is clicked, the "Next" button should be grey (to show that you can't continue)_ - **DONE**

**Comment by cedricbonhomme** [comment]
🎃 👍 🎃
