### ISSUE TITLE
Adding Links to report

### ISSUE THREAD

**Issue by eurodude** [CASES-LU/Fit4Cybersecurity#5]
Add links to both downloadable report and online report in the recommendation part...

like: For more Information, you can go to [CNPD](https://cnpd.public.lu/en.html)

It will add value to the person doing the self-assessment

**Comment by eurodude** [comment]
For python docx: [Add Hyperlink](https://stackoverflow.com/questions/47666642/adding-an-hyperlink-in-msword-by-using-python-docx)

For the Report: simple HTML link tads with "open in new tab/windows"

**Comment by ruslanbaidan** [comment]
We now moved to PDF, but it was added to word before also.
